site_name: CLUES - A Comprehensive Workflow for Integrating Geospatial Data in Health Research
nav:
  - Home: index.md
  - Geospatial Catalog: dataCatalog.md
  - User Guide: UserGuide.md
  - Examples: examples.md
  - Configuration: setup.md
  - 3rd Party Accounts: 3rdPartyAccounts.md
  - Data Sources: geospatial_data.md
  - Overview on Data: datalist.md
  - Data Usage: data_usage.md
  - Anticipated Result: anticipatedResult.md
  - Enrichment: enrichment.md
  - Notebooks: notebooks.md
  
theme:
  name: material
