site_name: CLUES - A Comprehensive Workflow for Integrating Geospatial Data in Health Research
nav:
  - Home: index.md
  - User Guide: UserGuide.md
  - Scripts and Notebook Examples: Scripts_Notebooks.md
  - Geospatial Data Catalog: dataCatalog.md
  - Data Format Specifications: data_formats.md
  - Applied Examples: Examples.md
  
markdown_extensions:
  - pymdownx.snippets

theme:
  name: material



