site_name: CLUES - A Comprehensive Workflow for Integrating Geospatial Data in Health Research
nav:
  - Home: index.md
  - User Guide: UserGuide.md
  - Geospatial Data Catalog: dataCatalog.md
  - Applied Examples: examples.md
  
markdown_extensions:
  - pymdownx.snippets

theme:
  name: material


