# Use official Python base image
FROM python:3.11-slim

# Set working directory inside container
WORKDIR /app

# Install git
RUN apt-get update && apt-get install -y git && rm -rf /var/lib/apt/lists/*

# Install nano editor
RUN apt-get update && apt-get install -y nano && rm -rf /var/lib/apt/lists/*

# Clone the repository
RUN git clone https://github.com/BIH-DMBS/CLUES.git 

# Set working dir to repo
WORKDIR /app/CLUES

# Install dependencies from requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy local config folder into container
COPY config/ ./config/
COPY configs_sources/ ./configs_sources/
COPY secrets/ ./secrets/

# Default command (can be overridden)
CMD ["bash"]